@startuml programme
header test
note "--> = fonction appel une autre fonction" as note1

map "Constantes " as constantes {
    NB_CLASSES_MAX => 20
    NB_TESTS_MAX => 10000
}

map "struct ResultClass" as resClass {
    classId => int
    nbCorrect => int
    nbTotal => int
}   

' Fonctions affichage
object "void displayResultsForEachClasses" as drfec {
     **arguments**
     - ResultClass results[]
     - int resultsLength
    --
    **do**
    affiche le tableau proprement sur base de results
}

object "void displayAccuracy" as da {
     **arguments**
     - double accuracy
    --
    **do**
    affiche la précision
}

object "void displayClass" as dc {
     **arguments**
     A editer
}

'Fonctions calcul

object "void processStats" as main {
     **arguments**
    - int realClasses[]
    - int estimateClasses[]
     - int length
     - ResultClass results[]
     --
     **do**
    boucle 'length' fois pour completer le tableau results

}

object "bool correctEstimation" as corEst {
    **arguments**
    - int real
    - int estimate
    --
    **do**
    vérifie si l'estimation est correct
    --
    **return**
    bool correct
}

object "double percent" as pct {
     **arguments**
    - int num
    - int den
     --
    **do**
     calcule le pourcentage sur base
     du ratio de 2 nombres
     renvoi 0 si den == 0
    --
    **return**
    double percent
}

object "int updateArray" as upAr {
     **arguments**
    - ResultClass results[]
    - int resultsLength
    - int class
    - bool isCorrect
     --
    **do**
    création classe dans résult si n'existe pas
     met à jour la classe envoyé
    --
    **return**
    int newLength
}

'note left of creClass : Précondition:\nla classe n'existe pas\ndans result

object "int createClass" as creClass {
    **arguments**
    - ResultClass results[]
    - int resultsLength
    - int class
    --
    **do**
    ajoute une nouvelle classe
    augmente la taille du tableau
    --
    **return**
    int newLength
}

object "bool classExist" as ce {
    **arguments**
    - int class
    - ResultClass results[]
    --
    **do**
    Vérifie si une classe existe déjà
    dans le tableau de résultats
    --
    **return**
    bool exist
}

object "double accuracy" as acc {
    **arguments**
    - ResultClass results[]
    - int resultsLength
    --
    **do**
    calcule la précision des résultats
    --
    **return**
    double accuracy
}

' Liens
main --> upAr
main --> corEst
upAr --> ce
upAr --> creClass
drfec --> pct
da --> acc

' note left of drfec: "bonjour"

@enduml